# Generated by Django 3.2 on 2022-10-20 06:23

import django.core.validators
from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': '이미 있는 제목'}, max_length=50)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10, '너무 짧다 10자이상써줘'), posts.validators.validate_symbols])),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
    ]
